const CACHE_VERSION = 'v-c673a82c';
const STATIC_CACHE = `study-mandarin-static-${CACHE_VERSION}`;
const RUNTIME_CACHE = `study-mandarin-runtime-${CACHE_VERSION}`;

// Generated by scripts/gen_sw.py — do not edit by hand
const ASSETS = (base) => [
    `${base}`,
    `${base}index.html`,
    `${base}page/flashcards/`,
    `${base}page/flashcards/index.html`,
    `${base}page/read/`,
    `${base}page/read/index.html`,
    `${base}page/zhuyin-trainer/`,
    `${base}page/zhuyin-trainer/index.html`,
    `${base}page/zhuyin-chart/`,
    `${base}page/zhuyin-chart/index.html`,
    `${base}page/karaoke/`,
    `${base}page/karaoke/index.html`,
    `${base}src/base.css`,
    `${base}src/colors.css`,
    `${base}src/flashcard.css`,
    `${base}src/modal.css`,
    `${base}page/flashcards/style.css`,
    `${base}page/read/style.css`,
    `${base}page/zhuyin-trainer/style.css`,
    `${base}page/zhuyin-chart/style.css`,
    `${base}page/karaoke/style.css`,
    `${base}src/util.js`,
    `${base}src/todo.js`,
    `${base}src/resources.js`,
    `${base}src/lib/papaparse.min.js`,
    `${base}page/flashcards/flashcard.js`,
    `${base}page/read/main.js`,
    `${base}page/zhuyin-trainer/main.js`,
    `${base}page/zhuyin-chart/main.js`,
    `${base}page/karaoke/karaoke.js`,
    `${base}src/font/NotoSansTC-Regular.ttf`,
    `${base}src/img/apple-touch-icon.png`,
    `${base}src/img/android-chrome-192x192.png`,
    `${base}src/img/android-chrome-512x512.png`,
    `${base}src/img/favicon-32x32.png`,
    `${base}src/img/favicon-16x16.png`,
    `${base}src/img/favicon.ico`,
    `${base}src/img/banner.png`,
    `${base}src/manifest.json`,
    `${base}data/flashcard-sets.json`,
    `${base}data/resources.json`,
    `${base}data/zhuyin-chart.json`,
    `${base}data/dictionary.csv`,
    `${base}data/songs/_songs.json`,
    `${base}data/flashcards/class/adjectives/adjectives-1.csv`,
    `${base}data/flashcards/class/adjectives/adjectives-2.csv`,
    `${base}data/flashcards/class/adjectives/adjectives-3.csv`,
    `${base}data/flashcards/class/basics/basics-1.csv`,
    `${base}data/flashcards/class/basics/basics-2.csv`,
    `${base}data/flashcards/class/basics/basics-3.csv`,
    `${base}data/flashcards/class/dining/dining-1.csv`,
    `${base}data/flashcards/class/dining/dining-2.csv`,
    `${base}data/flashcards/class/directions/directions-1.csv`,
    `${base}data/flashcards/class/dishes/dishes-1.csv`,
    `${base}data/flashcards/class/dishes/dishes-2.csv`,
    `${base}data/flashcards/class/dishes/dishes-3.csv`,
    `${base}data/flashcards/class/foods/foods-1.csv`,
    `${base}data/flashcards/class/foods/foods-2.csv`,
    `${base}data/flashcards/class/foods/foods-3.csv`,
    `${base}data/flashcards/class/kitchen/kitchen-1.csv`,
    `${base}data/flashcards/class/phrases/phrases-1.csv`,
    `${base}data/flashcards/class/phrases/phrases-2.csv`,
    `${base}data/flashcards/class/phrases/phrases-3.csv`,
    `${base}data/flashcards/class/time/time-1.csv`,
    `${base}data/flashcards/class/verbs/verbs-1.csv`,
    `${base}data/flashcards/class/verbs/verbs-10.csv`,
    `${base}data/flashcards/class/verbs/verbs-11.csv`,
    `${base}data/flashcards/class/verbs/verbs-2.csv`,
    `${base}data/flashcards/class/verbs/verbs-3.csv`,
    `${base}data/flashcards/class/verbs/verbs-4.csv`,
    `${base}data/flashcards/class/verbs/verbs-5.csv`,
    `${base}data/flashcards/class/verbs/verbs-6.csv`,
    `${base}data/flashcards/class/verbs/verbs-7.csv`,
    `${base}data/flashcards/class/verbs/verbs-8.csv`,
    `${base}data/flashcards/class/verbs/verbs-9.csv`,
    `${base}data/flashcards/unit/chengyu.csv`,
    `${base}data/flashcards/unit/everyday.csv`,
    `${base}data/flashcards/unit/external/china_institute.csv`,
    `${base}data/flashcards/unit/external/du_chinese.csv`,
    `${base}data/flashcards/unit/external/duolingo.csv`,
    `${base}data/flashcards/unit/external/reddit-1.csv`,
    `${base}data/flashcards/unit/external/reddit-2.csv`,
    `${base}data/flashcards/unit/external/reddit-sentences.csv`,
    `${base}data/flashcards/unit/measure_words.csv`,
    `${base}data/flashcards/unit/situations/online.csv`,
    `${base}data/flashcards/unit/situations/sports.csv`,
    `${base}data/flashcards/unit/situations/urban.csv`,
    `${base}data/flashcards/unit/structures/structures.csv`,
    `${base}data/flashcards/unit/structures/x_bu_y.csv`,
    `${base}data/flashcards/unit/structures/yue_lai_yue.csv`,
    `${base}data/flashcards/unit/structures/zai.csv`,
    `${base}data/flashcards/unit/taiwan/places.csv`,
    `${base}data/flashcards/unit/unsorted.csv`,
    `${base}data/songs/lo_tayu_childhood.csv`,
    `${base}data/songs/teresa_teng_i_only_care_about_you.csv`,
    `${base}data/songs/wei_bird_if_i_could.csv`,
    `${base}data/songs/wu_bai_norwegian_forest.csv`,
    `${base}data/songs/wu_bai_reunited.csv`,
];

self.addEventListener('install', event => {
  const assets = ASSETS(self.registration.scope);
  event.waitUntil(
    caches.open(STATIC_CACHE)
      .then(cache => cache.addAll(assets))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys()
      .then(keys => Promise.all(
        keys
          .filter(k => k !== STATIC_CACHE && k !== RUNTIME_CACHE)
          .map(k => caches.delete(k))
      ))
      .then(() => self.clients.claim())
  );
});

const RUNTIME_HOSTS = ['ajax.googleapis.com', 'fonts.googleapis.com', 'fonts.gstatic.com', 'cdnjs.cloudflare.com'];

self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET') return;

  const url = new URL(event.request.url);

  // Skip ads and audio — opaque responses from these bloat the cache
  if (url.hostname.includes('pagead') || url.hostname.includes('mdnkids.com')) return;

  if (url.origin === self.location.origin) {
    // Local assets: cache-first, fall back to network
    event.respondWith(
      caches.match(event.request).then(cached => {
        if (cached) return cached;
        return fetch(event.request).then(response => {
          const clone = response.clone();
          caches.open(STATIC_CACHE).then(cache => cache.put(event.request, clone));
          return response;
        });
      })
    );
  } else if (RUNTIME_HOSTS.some(h => url.hostname.includes(h))) {
    // CDN resources: network-first, cache for offline fallback
    event.respondWith(
      fetch(event.request)
        .then(response => {
          const clone = response.clone();
          caches.open(RUNTIME_CACHE).then(cache => cache.put(event.request, clone));
          return response;
        })
        .catch(() => caches.match(event.request))
    );
  }
});
