import os
import hashlib

FLASHCARDS_DIR = 'data/flashcards'
SONGS_DIR = 'data/songs'
OUTPUT = 'sw.js'

STATIC_CACHE_ASSETS = [
    # Pages
    '',
    'index.html',
    'page/flashcards/',
    'page/flashcards/index.html',
    'page/lists/',
    'page/lists/index.html',
    'page/read/',
    'page/read/index.html',
    'page/zhuyin-trainer/',
    'page/zhuyin-trainer/index.html',
    'page/zhuyin-chart/',
    'page/zhuyin-chart/index.html',
    'page/karaoke/',
    'page/karaoke/index.html',
    # CSS
    'src/base.css',
    'src/colors.css',
    'src/flashcard.css',
    'src/modal.css',
    'page/flashcards/style.css',
    'page/lists/style.css',
    'page/read/style.css',
    'page/zhuyin-trainer/style.css',
    'page/zhuyin-chart/style.css',
    'page/karaoke/style.css',
    # JS
    'src/util.js',
    'src/todo.js',
    'src/resources.js',
    'src/lib/papaparse.min.js',
    'page/flashcards/flashcard.js',
    'page/lists/list.js',
    'page/read/main.js',
    'page/zhuyin-trainer/main.js',
    'page/zhuyin-chart/main.js',
    'page/karaoke/karaoke.js',
    # Fonts + images
    'src/font/NotoSansTC-Regular.ttf',
    'src/img/apple-touch-icon.png',
    'src/img/android-chrome-192x192.png',
    'src/img/android-chrome-512x512.png',
    'src/img/favicon-32x32.png',
    'src/img/favicon-16x16.png',
    'src/img/favicon.ico',
    'src/img/banner.png',
    'src/manifest.json',
    # Static data
    'data/flashcard-sets.json',
    'data/resources.json',
    'data/zhuyin-chart.json',
    'data/dictionary.csv',
    'data/songs/_songs.json',
]


def collect_data_files():
    paths = []
    for root, _, files in os.walk(FLASHCARDS_DIR):
        for f in sorted(files):
            if f.endswith('.csv'):
                rel = os.path.join(root, f).replace('\\', '/')
                paths.append(rel)
    for f in sorted(os.listdir(SONGS_DIR)):
        if f.endswith('.csv'):
            paths.append(f'{SONGS_DIR}/{f}')
    return sorted(paths)


def compute_version(data_files):
    digest = hashlib.md5('\n'.join(data_files).encode()).hexdigest()[:8]
    return f'v-{digest}'


def gen_sw():
    data_files = collect_data_files()
    version = compute_version(data_files)
    all_assets = STATIC_CACHE_ASSETS + data_files

    asset_lines = '\n'.join(f"    `${{base}}{p}`," for p in all_assets)

    content = f"""const CACHE_VERSION = '{version}';
const STATIC_CACHE = `study-mandarin-static-${{CACHE_VERSION}}`;
const RUNTIME_CACHE = `study-mandarin-runtime-${{CACHE_VERSION}}`;

// Generated by scripts/gen_sw.py — do not edit by hand
const ASSETS = (base) => [
{asset_lines}
];

self.addEventListener('install', event => {{
  const assets = ASSETS(self.registration.scope);
  event.waitUntil(
    caches.open(STATIC_CACHE)
      .then(cache => cache.addAll(assets))
      .then(() => self.skipWaiting())
  );
}});

self.addEventListener('activate', event => {{
  event.waitUntil(
    caches.keys()
      .then(keys => Promise.all(
        keys
          .filter(k => k !== STATIC_CACHE && k !== RUNTIME_CACHE)
          .map(k => caches.delete(k))
      ))
      .then(() => self.clients.claim())
  );
}});

const RUNTIME_HOSTS = ['ajax.googleapis.com', 'fonts.googleapis.com', 'fonts.gstatic.com', 'cdnjs.cloudflare.com'];

self.addEventListener('fetch', event => {{
  if (event.request.method !== 'GET') return;

  const url = new URL(event.request.url);

  // Skip ads and audio — opaque responses from these bloat the cache
  if (url.hostname.includes('pagead') || url.hostname.includes('mdnkids.com')) return;

  if (url.origin === self.location.origin) {{
    // Local assets: cache-first, fall back to network
    event.respondWith(
      caches.match(event.request).then(cached => {{
        if (cached) return cached;
        return fetch(event.request).then(response => {{
          const clone = response.clone();
          caches.open(STATIC_CACHE).then(cache => cache.put(event.request, clone));
          return response;
        }});
      }})
    );
  }} else if (RUNTIME_HOSTS.some(h => url.hostname.includes(h))) {{
    // CDN resources: network-first, cache for offline fallback
    event.respondWith(
      fetch(event.request)
        .then(response => {{
          const clone = response.clone();
          caches.open(RUNTIME_CACHE).then(cache => cache.put(event.request, clone));
          return response;
        }})
        .catch(() => caches.match(event.request))
    );
  }}
}});
"""

    with open(OUTPUT, 'w') as f:
        f.write(content)
    print(f"Wrote {OUTPUT} (version: {version}, {len(all_assets)} assets, {len(data_files)} data files)")


if __name__ == '__main__':
    gen_sw()
